"""Add tables to improve the model

Revision ID: 001200079787
Revises: dad66d77b265
Create Date: 2025-04-19 08:01:44.789105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001200079787'
down_revision: Union[str, None] = 'dad66d77b265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financials_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=False),
    sa.Column('total_expenses', sa.Float(), nullable=False),
    sa.Column('total_savings', sa.Float(), nullable=False),
    sa.Column('total_investments', sa.Float(), nullable=False),
    sa.Column('net_worth', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('households_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.Enum('husband', 'wife', 'child', 'other', name='roleenum'), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investments_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('currentValue', sa.Float(), nullable=False),
    sa.Column('pricePerUnit', sa.Float(), nullable=True),
    sa.Column('unitsBought', sa.Float(), nullable=True),
    sa.Column('action', sa.Enum('buy', 'sell', 'transfer', 'deposit', 'withdraw', 'hold', name='actionenum'), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('savings_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('saving_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['saving_id'], ['savings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
   
  
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'currency',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.add_column('investments', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.drop_table('savings_logs')
    op.drop_table('investments_logs')
    op.drop_table('households_members')
    op.drop_table('financials_summaries')
    op.drop_table('households')
    # ### end Alembic commands ###
