"""Update Investment table

Revision ID: 0096e7e63be6
Revises: ffa2d51ec938
Create Date: 2025-10-30 09:34:41.946906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0096e7e63be6'
down_revision: Union[str, Sequence[str], None] = 'ffa2d51ec938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_column('value')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('value', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
