"""Add active option to houseHold

Revision ID: 07bbe60c330a
Revises: 001200079787
Create Date: 2025-04-21 16:58:23.844505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07bbe60c330a'
down_revision: Union[str, None] = '001200079787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""





def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
     # Reverse the operations in the downgrade function
    with op.batch_alter_table('households') as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('households_members') as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('currency',
            existing_type=sa.VARCHAR(length=9),
            nullable=True)

    op.create_table('_alembic_tmp_users')  # Recreate the dropped table if necessary
    
    # ### end Alembic commands ###
