"""Add currency to tables with amount

Revision ID: 0a35e71140c6
Revises: 49b2ba4140fc
Create Date: 2025-04-16 17:52:15.739425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a35e71140c6'
down_revision: Union[str, None] = '49b2ba4140fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- EXPENSES TABLE ---
    with op.batch_alter_table('expenses', recreate='always') as batch_op:
        batch_op.add_column(sa.Column(
            'currency',
            sa.Enum('euro', 'dolar', 'yuan', 'bitcoin', 'ethereum' 'usdc', 'dogecoin', 'litecoin','ripple', 'cardano' , name='currencyenum'),
            nullable=False
        ))
    # --- INCOMES TABLE ---
    with op.batch_alter_table('incomes', recreate='always') as batch_op:
        batch_op.add_column(sa.Column(
            'currency',
            sa.Enum('euro', 'dolar', 'yuan', 'bitcoin', 'ethereum' 'usdc', 'dogecoin', 'litecoin','ripple', 'cardano' , name='currencyenum'),
            nullable=False
        ))
    
    # --- INVESTMENTS TABLE ---
    with op.batch_alter_table('investments', recreate='always') as batch_op:
        batch_op.add_column(sa.Column(
            'currency',
            sa.Enum('euro', 'dolar', 'yuan', 'bitcoin', 'ethereum' 'usdc', 'dogecoin', 'litecoin','ripple', 'cardano' , name='currencyenum'),
            nullable=False
        ))
    
    # --- SAVINGS TABLE ---
    with op.batch_alter_table('savings', recreate='always') as batch_op:
        batch_op.add_column(sa.Column(
            'currency',
            sa.Enum('euro', 'dolar', 'yuan', 'bitcoin', 'ethereum' 'usdc', 'dogecoin', 'litecoin','ripple', 'cardano' , name='currencyenum'),
            nullable=False
        ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    op.drop_column('savings', 'currency')
    op.drop_column('investments', 'currency')
    op.drop_column('incomes', 'currency')
    op.drop_column('expenses', 'currency')
    # ### end Alembic commands ###
