"""Remove actives constraint

Revision ID: 10c92ee8b09f
Revises: 85e502f37c8b
Create Date: 2025-04-22 08:50:53.789104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c92ee8b09f'
down_revision: Union[str, None] = '85e502f37c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### commands auto generated by Alembic - please adjust! ###
    """ with op.batch_alter_table('households_members') as batch_op:
        batch_op.drop_column('actives') """

    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('currency',
                existing_type=sa.VARCHAR(length=9),
                nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'currency',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.add_column('households_members', sa.Column('actives', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
