"""add ignore_in_analysis to category_rules

Revision ID: 3d8e9f2a1b4c
Revises: f9c1c8a9bb59
Create Date: 2026-04-08 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8e9f2a1b4c'
down_revision: Union[str, Sequence[str], None] = 'f9c1c8a9bb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignore_in_analysis', sa.Boolean(), nullable=True, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_rules', schema=None) as batch_op:
        batch_op.drop_column('ignore_in_analysis')

    # ### end Alembic commands ###
