"""Add not nullable to all FK

Revision ID: 439f7ff03270
Revises: d823ebff734f
Create Date: 2025-04-25 07:25:44.071071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439f7ff03270'
down_revision: Union[str, None] = 'd823ebff734f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Data cleanup first!
    op.execute("UPDATE accounts SET user_id = 1 WHERE user_id IS NULL")
    op.execute("UPDATE accounts SET bank_id = 1 WHERE bank_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts') as batch_op:
        batch_op.alter_column('user_id',
                existing_type=sa.INTEGER(),
                nullable=False)
        batch_op.alter_column('bank_id',
                existing_type=sa.INTEGER(),
                nullable=False)

    with op.batch_alter_table('financials_summaries') as batch_op:
        batch_op.alter_column('user_id',
                existing_type=sa.INTEGER(),
                nullable=False)
        batch_op.alter_column('household_id',
                existing_type=sa.INTEGER(),
                nullable=False)

    with op.batch_alter_table('households_members') as batch_op:
        batch_op.alter_column('household_id',
                existing_type=sa.INTEGER(),
                nullable=False)
        batch_op.alter_column('user_id',
                existing_type=sa.INTEGER(),
                nullable=False)

    with op.batch_alter_table('incomes') as batch_op:
        batch_op.alter_column('user_id',
                existing_type=sa.INTEGER(),
                nullable=False)
        batch_op.alter_column('source_id',
                existing_type=sa.INTEGER(),
                nullable=False)
        batch_op.alter_column('category_id',
                existing_type=sa.INTEGER(),
                nullable=False)

    with op.batch_alter_table('investments') as batch_op:
        batch_op.alter_column('user_id',
                existing_type=sa.INTEGER(),
                nullable=False)
        batch_op.alter_column('account_id',
                existing_type=sa.INTEGER(),
                nullable=False)
        batch_op.alter_column('category_id',
                existing_type=sa.INTEGER(),
                nullable=False)

    with op.batch_alter_table('investments_logs') as batch_op:
        batch_op.alter_column('investment_id',
                existing_type=sa.INTEGER(),
                nullable=False)

    with op.batch_alter_table('savings') as batch_op:
        batch_op.alter_column('user_id',
                existing_type=sa.INTEGER(),
                nullable=False)
        batch_op.alter_column('account_id',
                existing_type=sa.INTEGER(),
                nullable=False)

    with op.batch_alter_table('savings_logs') as batch_op:
        batch_op.alter_column('saving_id',
                existing_type=sa.INTEGER(),
                nullable=False)
# ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('savings_logs', 'saving_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('savings', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('savings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('investments_logs', 'investment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('investments', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('investments', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('investments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('incomes', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('incomes', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('incomes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('households_members', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('households_members', 'household_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('financials_summaries', 'household_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('financials_summaries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('accounts', 'bank_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
