"""Expenses not nullable FK

Revision ID: 49b2ba4140fc
Revises: 5fd1b3a9ed85
Create Date: 2025-04-16 17:11:43.721157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b2ba4140fc'
down_revision: Union[str, None] = '5fd1b3a9ed85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # Step 1: Create a new table with the desired schema
    op.create_table(
        'expenses_new',
        sa.Column('id', sa.Integer, primary_key=True, nullable=False, autoincrement=True),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('description', sa.String),
        sa.Column('amount', sa.Float, nullable=False),
        sa.Column('date', sa.Date, nullable=False),
        sa.Column('user_id', sa.Integer, nullable=False),  # Set NOT NULL
        sa.Column('place_id', sa.Integer, nullable=False),  # Set NOT NULL
        sa.Column('category_id', sa.Integer, nullable=False),  # Set NOT NULL
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),  # Foreign key to users
        sa.ForeignKeyConstraint(['place_id'], ['places.id']),  # Foreign key to places
        sa.ForeignKeyConstraint(['category_id'], ['expenses_categories.id'])  # Foreign key to expenses_categories
    )

    # Step 2: Copy data from the old table to the new table
    op.execute("""
        INSERT INTO expenses_new (id, name, description, amount, date, user_id, place_id, category_id)
        SELECT id, name, description, amount, date, user_id, place_id, category_id FROM expenses
    """)

    # Step 3: Drop the old table
    op.drop_table('expenses')

    # Step 4: Rename the new table to the original table name
    op.rename_table('expenses_new', 'expenses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expenses', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('expenses', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('expenses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
