"""add type to sources to filter and add source to expenses

Revision ID: 631edb7ea0a1
Revises: 0096e7e63be6
Create Date: 2025-10-30 12:50:19.900380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631edb7ea0a1'
down_revision: Union[str, Sequence[str], None] = '0096e7e63be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ... (Sección de sources y NOT NULL de sources, que ya corregimos) ...

    # Eliminamos la tabla 'places' (si existía)

    # ...

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###




    # ### end Alembic commands ###
