"""add cards and link to expenses/incomes FINAL

Revision ID: 63829b82b09d
Revises: d10ca8146f0b
Create Date: 2026-04-02 00:40:32.429755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63829b82b09d'
down_revision: Union[str, Sequence[str], None] = 'd10ca8146f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('type', sa.Enum('credit', 'debit', 'revolving', name='cardtypeenum'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', 'last4', name='uq_card_account_last4')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignore_in_analysis', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('card_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_dedup_hash'), ['dedup_hash'], unique=False)
        batch_op.create_foreign_key(None, 'cards', ['card_id'], ['id'])

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incomes_dedup_hash'), ['dedup_hash'], unique=False)

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investments_dedup_hash'), ['dedup_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investments_dedup_hash'))

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incomes_dedup_hash'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_expenses_dedup_hash'))
        batch_op.drop_column('card_id')
        batch_op.drop_column('ignore_in_analysis')

    op.drop_table('cards')
    # ### end Alembic commands ###
