"""Update to avoid errors

Revision ID: 85e502f37c8b
Revises: 07bbe60c330a
Create Date: 2025-04-22 08:29:57.596081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e502f37c8b'
down_revision: Union[str, None] = '07bbe60c330a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
   
    # ### end Alembic commands ###
