"""Remove name from savings, and add fk in savings_logs fo sources

Revision ID: 8c04db668b45
Revises: d0c9c14e953f
Create Date: 2025-10-30 08:14:17.739541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c04db668b45'
down_revision: Union[str, Sequence[str], None] = 'd0c9c14e953f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_savings_source_id'), type_='foreignkey')
        batch_op.drop_column('name')
        batch_op.drop_column('source_id')

    with op.batch_alter_table('savings_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_savings_logs_source_id', 'sources', ['source_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('source_id')

    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_savings_source_id'), 'sources', ['source_id'], ['id'])

    # ### end Alembic commands ###
