"""add contrainst to better imports

Revision ID: a3374e91ae25
Revises: 574cf9d81f5b
Create Date: 2026-04-06 15:23:17.699599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3374e91ae25'
down_revision: Union[str, Sequence[str], None] = '574cf9d81f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_profile_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cards_import_origin_id'), ['import_origin_id'], unique=False)
        batch_op.create_foreign_key(None, 'import_profiles', ['import_profile_id'], ['id'])

    with op.batch_alter_table('import_origins', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('import_origins_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_import_origins_code'), ['code'], unique=True)

    with op.batch_alter_table('import_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_import_profiles_origin_id'), ['origin_id'], unique=False)
        batch_op.create_unique_constraint('uq_origin_profile_name', ['origin_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_origin_profile_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_import_profiles_origin_id'))
        batch_op.drop_column('version')
        batch_op.drop_column('file_type')

    with op.batch_alter_table('import_origins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_origins_code'))
        batch_op.create_unique_constraint(batch_op.f('import_origins_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cards_import_origin_id'))
        batch_op.drop_column('import_profile_id')

    # ### end Alembic commands ###
