"""add progile in accounts

Revision ID: c059fc3d2f51
Revises: a3374e91ae25
Create Date: 2026-04-06 15:26:03.531279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c059fc3d2f51'
down_revision: Union[str, Sequence[str], None] = 'a3374e91ae25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'import_profiles', ['import_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('import_profile_id')

    # ### end Alembic commands ###
