"""Add sources id to incomes and savings

Revision ID: d0c9c14e953f
Revises: cfb742949727
Create Date: 2025-10-30 07:25:19.300381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c9c14e953f'
down_revision: Union[str, Sequence[str], None] = 'cfb742949727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_savings_source_id', 'sources', ['source_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_savings_source_id', type_='foreignkey')
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###
