"""add currency

Revision ID: dad66d77b265
Revises: 0a35e71140c6
Create Date: 2025-04-18 11:02:40.653683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad66d77b265'
down_revision: Union[str, None] = '0a35e71140c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Expenses table
    with op.batch_alter_table('expenses') as batch_op:
        batch_op.alter_column(
            'currency',
            existing_type=sa.VARCHAR(length=12),
            type_=sa.Enum(
                'euro', 'dolar', 'yuan', 'bitcoin', 'ethereum', 'usdc', 'dogecoin',
                'litecoin', 'ripple', 'stellar', 'cardano', 'polkadot', 'solana',
                'shiba_inu', 'tron', name='currencyenum'
            ),
            existing_nullable=False
        )

    # Incomes table
    with op.batch_alter_table('incomes') as batch_op:
        batch_op.alter_column(
            'currency',
            existing_type=sa.VARCHAR(length=12),
            type_=sa.Enum(
                'euro', 'dolar', 'yuan', 'bitcoin', 'ethereum', 'usdc', 'dogecoin',
                'litecoin', 'ripple', 'stellar', 'cardano', 'polkadot', 'solana',
                'shiba_inu', 'tron', name='currencyenum'
            ),
            existing_nullable=False
        )

    # Investments table
    with op.batch_alter_table('investments') as batch_op:
        batch_op.alter_column(
            'currency',
            existing_type=sa.VARCHAR(length=12),
            type_=sa.Enum(
                'euro', 'dolar', 'yuan', 'bitcoin', 'ethereum', 'usdc', 'dogecoin',
                'litecoin', 'ripple', 'stellar', 'cardano', 'polkadot', 'solana',
                'shiba_inu', 'tron', name='currencyenum'
            ),
            existing_nullable=False
        )

    # Savings table
    with op.batch_alter_table('savings') as batch_op:
        batch_op.alter_column(
            'currency',
            existing_type=sa.VARCHAR(length=12),
            type_=sa.Enum(
                'euro', 'dolar', 'yuan', 'bitcoin', 'ethereum', 'usdc', 'dogecoin',
                'litecoin', 'ripple', 'stellar', 'cardano', 'polkadot', 'solana',
                'shiba_inu', 'tron', name='currencyenum'
            ),
            existing_nullable=False
        )

    # Users table (adding a column does not require batch mode, but you can use it for consistency)
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'currency',
            existing_type=sa.VARCHAR(length=12),
            type_=sa.Enum(
                'euro', 'dolar', 'yuan', 'bitcoin', 'ethereum', 'usdc', 'dogecoin',
                'litecoin', 'ripple', 'stellar', 'cardano', 'polkadot', 'solana',
                'shiba_inu', 'tron', name='currencyenum'
            ),
            existing_nullable=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    op.alter_column('savings', 'currency',
               existing_type=sa.Enum('euro', 'dolar', 'yuan', 'bitcoin', 'ethereum', 'usdc', 'dogecoin', 'litecoin', 'ripple', 'stellar', 'cardano', 'polkadot', 'solana', 'shiba_inu', 'tron', name='currencyenum'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.alter_column('investments', 'currency',
               existing_type=sa.Enum('euro', 'dolar', 'yuan', 'bitcoin', 'ethereum', 'usdc', 'dogecoin', 'litecoin', 'ripple', 'stellar', 'cardano', 'polkadot', 'solana', 'shiba_inu', 'tron', name='currencyenum'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.alter_column('incomes', 'currency',
               existing_type=sa.Enum('euro', 'dolar', 'yuan', 'bitcoin', 'ethereum', 'usdc', 'dogecoin', 'litecoin', 'ripple', 'stellar', 'cardano', 'polkadot', 'solana', 'shiba_inu', 'tron', name='currencyenum'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.alter_column('expenses', 'currency',
               existing_type=sa.Enum('euro', 'dolar', 'yuan', 'bitcoin', 'ethereum', 'usdc', 'dogecoin', 'litecoin', 'ripple', 'stellar', 'cardano', 'polkadot', 'solana', 'shiba_inu', 'tron', name='currencyenum'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###
