"""refactor accounts

Revision ID: e575401010de
Revises: 
Create Date: 2026-03-11 19:49:53.867205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e575401010de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.Enum('euro', 'dolar', 'yuan', 'bitcoin', 'ethereum', 'usdc', 'dogecoin', 'litecoin', 'ripple', 'stellar', 'cardano', 'polkadot', 'solana', 'shiba_inu', 'tron', name='currencyenum'), nullable=False))
        batch_op.alter_column('iban',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_expenses_user_id'))
        batch_op.drop_constraint(batch_op.f('expenses_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_incomes_user_id'))
        batch_op.drop_constraint(batch_op.f('incomes_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.drop_index(batch_op.f('ix_investments_user_id'))
        batch_op.drop_constraint(batch_op.f('investments_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_savings_user_id'))
        batch_op.drop_constraint(batch_op.f('savings_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('savings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('savings_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_savings_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('investments_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_investments_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('amount')
        batch_op.drop_column('description')

    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('incomes_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_incomes_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('expenses_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_expenses_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('iban',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
