/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Description = string | null;
export type Iban = string | null;
export type CurrencyEnum =
  | "€"
  | "$"
  | "¥"
  | "₿"
  | "Ξ"
  | "USDC"
  | "DOGE"
  | "LTC"
  | "XRP"
  | "XLM"
  | "ADA"
  | "DOT"
  | "SOL"
  | "SHIB"
  | "TRX";
export type InitialBalance = number | string;
export type Balance = number | string | null;
export type Active = boolean;
export type BankId = number;
export type ImportOriginId = number | null;
export type ImportProfileId = number | null;
/**
 * @minItems 1
 */
export type UserIds = [number, ...number[]];

export interface AccountCreate {
  name: Name;
  description?: Description;
  iban?: Iban;
  currency: CurrencyEnum;
  initial_balance?: InitialBalance;
  balance?: Balance;
  active?: Active;
  bank_id: BankId;
  import_origin_id?: ImportOriginId;
  import_profile_id?: ImportProfileId;
  user_ids: UserIds;
  [k: string]: unknown;
}
