/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CreatedAt = string;
export type UpdatedAt = string;
export type DeletedAt = string | null;
export type Name = string;
export type Last4 = string | null;
export type CardTypeEnum = "credit" | "debit" | "revolving";
export type Active = boolean;
export type AccountId = number;
export type Id = number;

export interface CardRead {
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  deleted_at?: DeletedAt;
  name: Name;
  last4?: Last4;
  type: CardTypeEnum;
  active?: Active;
  account_id: AccountId;
  id: Id;
  [k: string]: unknown;
}
