/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OriginId = number;
export type Name = string;
export type HeaderRowGuess = number;
export type Active = boolean;

export interface ImportProfileCreate {
  origin_id: OriginId;
  name: Name;
  header_row_guess?: HeaderRowGuess;
  columns: Columns;
  active?: Active;
  [k: string]: unknown;
}
export interface Columns {
  [k: string]: string[];
}
