/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CreatedAt = string;
export type UpdatedAt = string;
export type DeletedAt = string | null;
export type SourceName = string;
export type Description = string | null;
export type Active = boolean;
export type Type = "income" | "saving" | "investment" | "expense" | "other";
export type Id = number;

export interface SourceRead {
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  deleted_at?: DeletedAt;
  name: SourceName;
  description?: Description;
  active?: Active;
  type: Type;
  id: Id;
  [k: string]: unknown;
}
