/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CreatedAt = string;
export type UpdatedAt = string;
export type DeletedAt = string | null;
export type Name = string;
export type Surname1 = string;
export type Surname2 = string | null;
export type Dni = string;
export type Email = string | null;
export type Active = boolean;
export type Telephone = number | null;
import { UserRoleEnum } from "@core/const/UserRole.enum";
export type Id = number;

export interface UserRead {
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  deleted_at?: DeletedAt;
  name: Name;
  surname1: Surname1;
  surname2?: Surname2;
  dni: Dni;
  email?: Email;
  active?: Active;
  telephone?: Telephone;
  role?: UserRoleEnum;
  id: Id;
  [k: string]: unknown;
}
