/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
import { CardEnum } from "@core/const/Card.enum";

export type Id = number;
export type Name = string;
export type Last4 = string | null;
export type CardTypeEnum = CardEnum;
export type Active = boolean;
export type AccountId = number;
export type ImportSourceCode = string | null;
export interface CardBase {
  id?: Id;
  name: Name;
  last4?: Last4;
  type: CardTypeEnum;
  active?: Active;
  account_id: AccountId;
  import_source_code?: string;
}