/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type Id = number;
export type Name = string;
export type Description = string | null;
export type Active = boolean;
export interface SelectBankOption {
  value: string | number; // El valor que se enviará al backend (ej: el ID del banco)
  label: string;         // El texto visible en el desplegable (ej: el nombre del banco)
}
export interface BankBase {
  id: Id
  name: Name;
  description?: Description;
  active?: Active;
  [k: string]: unknown;
}
