/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Date = string;
export type TotalIncome = number;
export type TotalExpenses = number;
export type TotalSavings = number;
export type TotalInvestments = number;
export type NetWorth = number;
export type UserId = number;
export type HouseholdId = number;

export interface FinancialSummaryBase {
  name: Name;
  date: Date;
  total_income: TotalIncome;
  total_expenses: TotalExpenses;
  total_savings: TotalSavings;
  total_investments: TotalInvestments;
  net_worth: NetWorth;
  user_id: UserId;
  household_id: HouseholdId;
  [k: string]: unknown;
}
