/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Date = string;
export type Currentvalue = number;
export type Priceperunit = number;
export type Unitsbought = number;
export type ActionEnum = "buy" | "sell" | "transfer" | "deposit" | "withdraw" | "hold";
export type Note = string;
export type InvestmentId = number;

export interface InvestmentLogBase {
  date: Date;
  currentValue: Currentvalue;
  pricePerUnit: Priceperunit;
  unitsBought: Unitsbought;
  action: ActionEnum;
  note: Note;
  investment_id: InvestmentId;
  [k: string]: unknown;
}
