/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type Id = number;
export type Name = string;
export type Address = string | null;
export type Description = string | null;
export type Active = boolean;

export interface PlaceBase {
  id:Id;
  name: Name;
  address?: Address;
  description?: Description;
  active?: Active;
  [k: string]: unknown;
}
