/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type Id = number;
export type Name = string;
export type Description = string | null;
export type Active = boolean;

export interface SourceBase {
  id: Id;
  name: Name;
  description?: Description;
  active?: Active;
  //[k: string]: unknown;
}
