/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type Id = number;
export type Name = string;
export type Surname1 = string;
export type Surname2 = string | null;
export type Dni = string | null;
export type Email = string | null;
export type Active = boolean;
export type Telephone = number | null;
export type UserRoleType = 'administrator' | 'editor' | 'user' | 'guest';
export type Password = string;

export interface RoleOption {
    value: UserRoleType;
    viewValue: string;
}

export const USER_ROLE_OPTIONS: RoleOption[] = [
    { value: 'administrator', viewValue: 'Administrador' },
    { value: 'editor', viewValue: 'Editor' },
    { value: 'user', viewValue: 'Usuario' },
    { value: 'guest', viewValue: 'Invitado' },
];

export interface SelectUserOption {
  value: string | number;
  label: string;
}
export interface UserBase {
  id: Id;
  name: Name;
  surname1: Surname1;
  surname2?: Surname2;
  dni?: Dni;
  email?: Email;
  active?: Active;
  telephone?: Telephone;
  role: UserRoleType;
  password: Password;
  //[k: string]: unknown;
}
