/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { RoleEnum } from '@core/const/Role.enum';
export type HouseholdId = number;
export type UserId = number;
export type Active = boolean;

export interface HouseholdMemberBase {
  id?: number;
  role: RoleEnum;
  household_id: HouseholdId;
  user_id: UserId;
  active?: Active;
}
