/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type OriginId = number;
export type Name = string;
export type HeaderRowGuess = number;
export type Columns = {
  [k: string]: string[];
};
export type Active = boolean;

export type ImportProfileCreate = Omit<ImportProfileBase, 'id' | 'created_at' | 'updated_at' | 'deleted_at'>;

export interface ImportProfileBase {
  origin_id: OriginId;
  name: Name;
  header_row_guess?: HeaderRowGuess;
  columns: Columns;
  active?: Active;
  id: number;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  [k: string]: unknown;
}


