/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CreatedAt = string;
export type UpdatedAt = string;
export type DeletedAt = string | null;
export type Code = string;
export type Name = string;
export type Active = boolean;
export type Id = number;

export interface ImportOriginBase {
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  deleted_at?: DeletedAt;
  code: Code;
  name: Name;
  active?: Active;
  id: Id;
  [k: string]: unknown;
}