/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type Description = string | null;
export type Amount = number;
export type Date = string;
export type CurrencyEnum =
  | "€"
  | "$"
  | "¥"
  | "₿"
  | "Ξ"
  | "USDC"
  | "DOGE"
  | "LTC"
  | "XRP"
  | "XLM"
  | "ADA"
  | "DOT"
  | "SOL"
  | "SHIB"
  | "TRX";
export type AccountId = number;

export interface SavingBase {
  id?: number;
  description: Description;
  amount: Amount;
  date: Date;
  currency: CurrencyEnum;
  account_id: AccountId;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string | null;
}
