/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { CurrencyEnum } from "@core/const/Currency.enum";

export type Id = number;
export type Name = string;
export type Description = string | null;
export type Iban = string;
export type Balance = number;
export type Active = boolean;
export type BankId = number;
export type UserId = number;
export type UserIds = number[];
export type ImportOriginId = number;
export type ImportProfileId = number;

export interface AccountBase {
  id?: Id;
  name: Name;
  description?: Description;
  iban: Iban;
  balance: Balance;
  currency: CurrencyEnum;
  active?: Active;
  bank_id: BankId;
  user_id: UserId;
  user_ids?: UserIds;
  users?: any[];
  import_origin_id?: ImportOriginId;
  import_profile_id?: ImportProfileId;
  users?: any[]; // Users added manually
}
