/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Description = string | null;
export type Active = boolean;

export interface SourceBase {
  id?: number;
  name: Name;
  description?: Description;
  active?: Active;
  created_at?: string;
  updated_at?: string;
  deleted_at?: string | null;
  [k: string]: unknown;
}
