/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Surname1 = string;
export type Surname2 = string | null;
export type Dni = string;
export type Email = string | null;
export type Active = boolean;
export type Telephone = number | null;
export type UserRole = 'administrator' | 'editor' | 'user' | 'guest';



export const USER_ROLE_OPTIONS: UserRole[] = ['administrator', 'editor', 'user', 'guest'];


export interface UserBase {
  id?: number;
  name: Name;
  surname1: Surname1;
  surname2?: Surname2;
  dni: Dni;
  email?: Email;
  active?: Active;
  telephone?: Telephone;
  password?: string;
  role?: UserRole;
  created_at?: string;
  updated_at?: string;
}
