# generated by datamodel-codegen:
#   filename:  UserBase_schema.json
#   timestamp: 2025-04-29T21:30:38+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, EmailStr, Field


class UserBase(BaseModel):
    name: str = Field(..., title='Name')
    surname1: str = Field(..., title='Surname1')
    surname2: Optional[str] = Field(None, title='Surname2')
    dni: Optional[str] = Field(None, title='Dni')
    email: Optional[EmailStr] = Field(None, title='Email')
    active: Optional[bool] = Field(True, title='Active')
    telephone: Optional[int] = Field(None, title='Telephone')
