/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
import { CurrencyEnum } from "@core/const/currency.enum";
export type Description = string;
export type Amount = number;
export type Date = string;
export type AccountId = number;
export type CategoryId = number;

export interface InvestmentBase {
  id?: number;
  description: Description;
  amount: Amount;
  date: Date;
  currency: CurrencyEnum;
  account_id: AccountId;
  category_id: CategoryId;
}
