/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
import { ActionEnum } from '@core/const/Action.enum';
export type Date = string;
export type Currentvalue = number;
export type Priceperunit = number;
export type Quantity = number;
export type Note = string;
export type InvestmentId = number;

export interface InvestmentLogBase {
  id?: number;
  date: Date;
  current_value?: Currentvalue;
  price_per_unit?: Priceperunit;
  quantity?: Quantity;
  action: ActionEnum;
  note: Note;
  investment_id: InvestmentId;
}
